### ISSUE TITLE
Does not work with neovim on ubuntu15.04

### ISSUE THREAD

**Issue by ishankhare07** [kristijanhusak/vim-hybrid-material#1]
the installation works fine
`colorscheme hybrid_material` does not throw any errors
but nothing really happens
infact my syntax highlighting disappears
can't even re-enable it with `syntax on`
restarting nvim brings back the syntax highlighting though

**Comment by kristijanhusak** [comment]
hybrid_material works only for graphical vim (GVim, MacVim), I havent tested it on neovim.

**Comment by kristijanhusak** [comment]
I guess it has something to do with this https://github.com/w0ng/vim-hybrid/issues/27

**Comment by ishankhare07** [comment]
also, is there any way i don't need to type `colorscheme hybrid_material`
i tried putting it in my .nvimrc on OS X but didn't work

**Comment by kristijanhusak** [comment]
I'll try to fix it, will let you know.

**Comment by kristijanhusak** [comment]
@ishankhare07 
I added the fix, but i cannot check it because i'm on ubuntu. Please update and check if it works properly now.

**Comment by ishankhare07** [comment]
```bash
Error detected while processing /Users/ishan/.nvimrc:
line   17:
E185: Cannot find color scheme 'hybrid_material'
Press ENTER or type command to continue
```

this i added in .nvimrc:
```viml
colorscheme hybrid_material
```

`:colorscheme hybrid_material` still works

**Comment by kristijanhusak** [comment]
How you installed it? Via package manager or someway else?
Can you send me the link to your nvimrc so i can test it?
also, type `:echo &t_Co` in the nvim command line and tell me what it returns.

**Comment by ishankhare07** [comment]
`:echo &t_Co` return 256
i installed via homebrew
[here](https://github.com/ishankhare07/dotfiles/blob/master/.nvimrc) is my .nvimrc file
**i commented out colorscheme line for now**

**Comment by kristijanhusak** [comment]
Colorscheme can be set only after plugin manager has finished package instantiation (after vundle#end). So just move `colorscheme hybrid_material` from line 17 to line 39.

**Comment by ishankhare07** [comment]
it still needs work though,
i can't see line numbers properly etc.
this is on OS X
![screen shot 2015-07-09 at 4 43 16 pm](https://cloud.githubusercontent.com/assets/7482025/8593905/a693df8e-2659-11e5-8fcd-8f7d6e2c5371.png)

and just curious, you said you're on ubuntu, but hybrid_material doesn't work on ubuntu yet, then how did you test it?

**Comment by kristijanhusak** [comment]
As i said, it's not tested on neovim. Here's screenshot from neovim on ubuntu:
![screenshot_2015-07-09_13-24-47](https://cloud.githubusercontent.com/assets/1782860/8594090/f566fc48-263d-11e5-8724-a46dabd7411a.png)

Where did i put that it's not working on the ubuntu? Material one works properly with GUI Vims(Gvim/Macvim), and reverse one works for both terminal and GUI Vim.
