### ISSUE TITLE
Different colors

### ISSUE THREAD

**Issue by sethen** [kristijanhusak/vim-hybrid-material#13]
Hey there,

I am new to Vim and trying to install this theme.  I copied the `hybrid_reverse` color theme into my `.vim/colors` directory and set my `.vimrc` accordingly but I am not seeing the colors I think I should.  It looks like it's sort of close but not quite.

My `.vimrc` looks like:

```
set background=dark
colorscheme hybrid_reverse
```

And here is my output in Vim

![screenshot from 2016-07-19 15-55-02](https://cloud.githubusercontent.com/assets/1493530/16964453/7bf84fb0-4dc9-11e6-9d4f-8f04c68d2b85.png)

Any thoughts here?

**Comment by kristijanhusak** [comment]
Did you install base 16 builder maybe?
