### ISSUE TITLE
Airline not rendering as it should be

### ISSUE THREAD

**Issue by PezCoder** [kristijanhusak/vim-hybrid-material#15]
#### Extending > https://github.com/kristijanhusak/vim-hybrid-material/issues/9
hey @kristijanhusak,  I checked your vim files.. & Since i'm using vim in iterm2 I followed your base-16 instructions to put the correct colors in place. 
I'm using `Inconsolata for Powerline Plus Nerd File Types.otf` for my iterm2 (ascii + normal) + vim-devicons.
I'm not getting those details due to some reasons here's my vimrc stuff related to this theme:

```
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

set background=dark
let base16colorspace=256
colorscheme base16-material

let g:airline_powerline_fonts = 1                                               "Enable powerline fonts
let g:airline_theme = "hybrid"                                                  "Set theme to powerline default theme
let g:airline_section_y = '%{substitute(getcwd(), expand("$HOME"), "~", "g")}'  "Set relative path
let g:airline#extensions#whitespace#enabled = 0                                 "Disable whitespace extension
let g:airline#extensions#tabline#enabled = 1                                    "Enable tabline extension
let g:airline#extensions#tabline#left_sep = ' '                                 "Left separator for tabline
let g:airline#extensions#tabline#left_alt_sep = '│'                             "Right separator for tabline

```

Points to note: 
1. I have manually downloaded the base16-material version provide by you for vim terminal users & installed the same on my iterm2. No issue in colors (It looks just great !)
2. I'm assuming that `let g:airline_theme = "hybrid" ` < this hybrid theme is coming from airline-themes.
3. The icons are working fine.

**How can i get the perfect boxes & arrow as mentioned by @jrolfs for top & bottom bar of airline?**

Here's the screenshot of my current system: (Mac OSX, iterm2, VIM)
![image](https://cloud.githubusercontent.com/assets/8057916/18931277/1eb7d020-85e9-11e6-8112-ecd0a8e7c999.png)

**Comment by kristijanhusak** [comment]
Did you try with some other color schemes? Does issue exist on those?
I think there are some differences in each system vim version (MacOS, Win, Linux), so i'm not sure you can make it look 100% same. I'm on Xubuntu.

For the issue with airline, i found this on the airline repo:

https://github.com/vim-airline/vim-airline/issues/1244

Which vim version are you using?
You should try upgrading both vim and airline to the latest.

**Comment by PezCoder** [comment]
No with other color schemes (Oceanic next) & even with base16-material as color scheme & no theme for airlines gives me those boxes (but it's looking ugly as you can see).
![image](https://cloud.githubusercontent.com/assets/8057916/18960755/7355570c-8688-11e6-9daf-a714cf4b1857.png)

My vim version is: 7.4.52

Airline is on the latest version & even it's readme says (``Supports 7.2 as the minimum Vim version.``)

I read the link, the issue is exactly the same as he mentioned but not solved yet. I guess some of vim-airline are giving correct colors & boxes while other aren't. No idea why.

**Comment by PezCoder** [comment]
Anyways thanks for your help. There are quite a good collection of themes for airline, I'll pick one.
One last thing, The cursor in you VIM i.e the current line was highlighted. How did you achieve that ? I tried `` set cursorline`` but due to some reason, it's not making any effect.
