### ISSUE TITLE
How to make airline display nicely?

### ISSUE THREAD

**Issue by retroalgic** [kristijanhusak/vim-hybrid-material#16]
I set up the theme with your [vimfiles](https://github.com/kristijanhusak/vimfiles) actually. I only changed
`set guifont=InconsolataForPowerline\ Nerd\ Font\ Medium\ 12` 
to 
`set guifont=Inconsolata\ For\ Powerline\ Plus\ Nerd\ File\ Types:h12`

But my airline looks like this
<img width="1440" alt="bad" src="https://cloud.githubusercontent.com/assets/10691963/24683052/87a0e660-19cf-11e7-9483-a561ca83f1a2.png">

While the one in your screenshot looks like this
![good](https://cloud.githubusercontent.com/assets/10691963/24683078/a2bb9fe4-19cf-11e7-9558-726ed452aa30.png)

(I'm using MacVim, vim 8.0.525)

Do you know how to expand airline on the top and bottom equally?

**Comment by retroalgic** [comment]
Okay, I manage to make it work in iTerm by adjusting Non-ASCII Font size and line-spacing. I didn't find a good combination though as I prefer larger font size. 

Also it won't work in MacVim because I can only adjust linespace for it, which doesn't make it look nicer.

**Comment by kristijanhusak** [comment]
Screenshots are from linux. Yeah, it's linespacing issue, on both MacVim and iTerm. Nothing can be really done about it.

**Comment by retroalgic** [comment]
For anyone who want line to scale nicely on MacOS, the only solution I found is [NyaoVim](https://github.com/rhysd/NyaoVim). But arrows look ugly when using it as it's built on Electron.
