### ISSUE TITLE
Can't apply hybrid_material

### ISSUE THREAD

**Issue by onirusama** [kristijanhusak/vim-hybrid-material#17]
Hi sir, i am new in vim and i really love like this theme. I want to use that hybrid_material. I'm using ubuntu and zsh as my shell. After installation i set:
````
    set background=dark
    colorscheme hybrid_material
````
but this look not some with the priview. I set colorscheme hybrid_material but i get hybrid_reverse. I try change colorscheme to hybrid_reverse but still same result.

sory, for bad english.

**Comment by kristijanhusak** [comment]
You need to install base16-builder to achieve something like that. Check the readme here https://github.com/kristijanhusak/vim-hybrid-material#vim
