### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by emprovements** [kristijanhusak/vim-hybrid-material#21]
Hi,
Is it possible to add option for transparent background? I often use it in terminal.
If not, could you give me some hint how to change it in the theme file?

Thanks ;-)

**Comment by emprovements** [comment]
so I hacked it by this for now
`let s:palette.cterm.background = { 'dark' : "none"              , 'light' : "254" }`

**Comment by kristijanhusak** [comment]
Sure, i'll add it.

**Comment by kristijanhusak** [comment]
@emprovements 
add this before your `colorscheme` call:
```vimL
let g:hybrid_transparent_background = 1
```

**Comment by emprovements** [comment]
Perfect, thanks ;-)
