### ISSUE TITLE
italic and bold don't work

### ISSUE THREAD

**Issue by H-ZeX** [kristijanhusak/vim-hybrid-material#24]
the code below work 
```vim
let g:enable_italic_font = 1
let g:enable_bold_font = 1
syntax enable
colorscheme  hybrid_material  " 设定配色方案
set background=dark
```

the code below don't work
```vim
syntax enable
colorscheme  hybrid_material  " 设定配色方案
set background=dark
let g:enable_italic_font = 1
let g:enable_bold_font = 1
```
i should source the .gvimrc one more time after open the gvim, or it don't work

i create a new .gvimrc which only include the code above to test (and the .vimrc had been mv tho another name), situation is same.

**Comment by HideOnLie** [comment]
Thank your message.my situation is same as you .I have confused it  with a long time.I hope the author can get resolved.

**Comment by kristijanhusak** [comment]
Variables are not set at the moment colorscheme is set, that's why you have to set them before `colorscheem hybrid_material`.
