### ISSUE TITLE
Highlighted line not transparent in transparent terminal

### ISSUE THREAD

**Issue by astier** [kristijanhusak/vim-hybrid-material#28]
On a transparent terminal with `let g:hybrid_transparent_background = 1` the highlighted line is not transparent.
![2019-02-22-000826_936x516_scrot](https://user-images.githubusercontent.com/36510152/53208151-0fa33980-3636-11e9-869e-d830aa6dc4dd.png)

**Comment by astier** [comment]
Is it vims issue or can it be solved with your plugin?
Great work btw!

**Comment by HoneyBearCodes** [comment]
I have the same issue but with the Neovim
