### ISSUE TITLE
Airline

### ISSUE THREAD

**Issue by charlespeters** [kristijanhusak/vim-hybrid-material#7]
is there a special setting to get airline and the status bar to assume the theme?

**Comment by kristijanhusak** [comment]
I'm using [hybrid](https://github.com/bling/vim-airline/blob/master/autoload/airline/themes/hybrid.vim) theme which suites well for me.

**Comment by charlespeters** [comment]
oh it's in the airline package already, thanks!

**Comment by olimorris** [comment]
@kristijanhusak You should mention this in the readme as most people's existing airline theme will clash with the hybrid material theme.

**Comment by kristijanhusak** [comment]
@olimorris I added it. https://github.com/kristijanhusak/vim-hybrid-material#airline
Thanks.
