### ISSUE TITLE
Green line for current line and line numbers

### ISSUE THREAD

**Issue by nicohvi** [kristijanhusak/vim-hybrid-material#8]
Great looking skin, good work! 

I followed the instructions for installing the theme for vim running in iterm2, but I'm running into some problems. Things look like this:

<img width="574" alt="screen shot 2015-11-20 at 12 48 22" src="https://cloud.githubusercontent.com/assets/430875/11299215/29a55a80-8f85-11e5-8713-6b30035f78fe.png">
<img width="1655" alt="screen shot 2015-11-20 at 12 48 52" src="https://cloud.githubusercontent.com/assets/430875/11299216/29a8ce0e-8f85-11e5-8814-403f1bd85572.png">

Any idea what could be going on?

**Comment by kristijanhusak** [comment]
I'm not MacOS user, but this may help you https://github.com/chriskempson/base16-vim#troubleshooting . Try it out and let me know.

**Comment by kristijanhusak** [comment]
@nicohvi did you manage to set it up?

**Comment by ELD** [comment]
@nicohvi Which color scheme are you using for your terminal? Are you using the bash scripts that were recommended in the readme for terminal Vim?

If you can answer those questions, I can help you further.

**Comment by PezCoder** [comment]
I had this issue.. & `let base16colorspace=256` solved my problem. Thanks @kristijanhusak

**Comment by kristijanhusak** [comment]
@PezCoder great. I'll close this, since @nicohvi didn't give any answer, i guess he fixed it up.
